
name: App Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
  
    runs-on: ubuntu-latest

    steps:
    - name: Teste Echo
      uses: actions/checkout@v2
      with:
        host: ${{secrets.SSH_HOST}} 
        key: ${{secrets.SSH_KEY}} 
        username: ${{secrets.SSH_USERNAME}}  
      
   script:

  echo -e "Deploy feito com Sucesso"
